#!/bin/bash
# boot-via-rubu.sh — boot the asterkube node through RUBU, our pure-Rust UEFI
# bootloader (https://github.com/jboero/rubu), instead of GRUB2. This closes the
# last C gap in the stack: GRUB2 was the only C component in the boot path; rubu
# replaces it with a #![no_std], zero-C bootloader that measures the boot into a
# TPM and hands off to the Asterinas kernel via the Linux EFI-handover protocol.
#
# The result is a boot chain with NO C at all: rubu (Rust) -> Asterinas (Rust
# kernel) -> Go init/kubelet. Verified: the node still joins a cluster and reaches
# Ready when booted this way.
#
# Unlike the released ISO (a GRUB2 multiboot2 image), rubu boots a Linux-protocol
# bzImage + a separate initramfs, so this is a build-from-source demo:
#
#   1. Build the EFI-handover bzImage (in the OSDK build container):
#        docker exec asterkube bash -lc \
#          'cd /root/asterinas/kernel && cargo osdk build \
#             --grub-boot-protocol linux --boot-method qemu-direct'
#      -> asterinas/target/osdk/aster-kernel-osdk-bin        (the bzImage)
#      Our zero-C initramfs is already at
#        asterinas/test/initramfs/build/initramfs.cpio.gz    (built by zero-c-initramfs.sh)
#
#   2. (optional) Mint a cluster join bundle so the node registers + goes Ready:
#        scripts/asterkube-join.sh -n asterkube -s <apiserver-ip:port>
#
#   3. Boot it through rubu:
#        RUBU=../rubu \
#        KERNEL=asterinas/target/osdk/aster-kernel-osdk-bin \
#        INITRD=asterinas/test/initramfs/build/initramfs.cpio.gz \
#        JOIN_BUNDLE=asterkube-join.img \
#        scripts/boot-via-rubu.sh
#
# Env:
#   RUBU         path to a rubu checkout (default: ../rubu). rubu.efi is built if absent.
#   KERNEL       Linux-protocol Asterinas bzImage (see step 1)
#   INITRD       zero-C initramfs.cpio.gz
#   JOIN_BUNDLE  optional ext2 join bundle (asterkube-join.sh) -> node joins a cluster
#   CMDLINE      kernel cmdline (default: the standard asterkube kcmd_args)
#   TIMEOUT      seconds before the VM is killed (default: 0 = run until Ctrl-C / ACPI)
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
RUBU=${RUBU:-$(cd "$REPO/.." && pwd)/rubu}
KERNEL=${KERNEL:-$REPO/asterinas/target/osdk/aster-kernel-osdk-bin}
INITRD=${INITRD:-$REPO/asterinas/test/initramfs/build/initramfs.cpio.gz}
JOIN_BUNDLE=${JOIN_BUNDLE:-}
CMDLINE=${CMDLINE:-"SHELL=/bin/sh LOGNAME=root HOME=/ USER=root PATH=/bin:/sbin:/usr/bin console=hvc0 ASTERKUBE_PERSIST=1 init=/sbin/init"}
TIMEOUT=${TIMEOUT:-0}

[ -d "$RUBU" ]    || { echo "!! rubu checkout not found at $RUBU — clone https://github.com/jboero/rubu (or set RUBU=)" >&2; exit 1; }
[ -f "$KERNEL" ]  || { echo "!! missing bzImage $KERNEL — build it (see the header, step 1)" >&2; exit 1; }
[ -f "$INITRD" ]  || { echo "!! missing initramfs $INITRD — run scripts/zero-c-initramfs.sh" >&2; exit 1; }

# Build rubu.efi if it isn't there. rubu targets x86_64-unknown-uefi on a rustup
# nightly; use rubu's own build script.
EFI="$RUBU/target/x86_64-unknown-uefi/release/rubu.efi"
if [ ! -f "$EFI" ]; then
  echo "==> building rubu.efi ($RUBU/tools/build.sh)"
  ( cd "$RUBU" && bash tools/build.sh )
fi
[ -f "$EFI" ] || { echo "!! rubu.efi not built at $EFI" >&2; exit 1; }

# OVMF (UEFI firmware).
find_ovmf() { for d in /usr/share/edk2/ovmf /usr/share/OVMF /usr/share/qemu /usr/share/edk2-ovmf/x64; do
  for c in OVMF_CODE.fd OVMF_CODE.4m.fd OVMF_CODE_4M.fd; do [ -f "$d/$c" ] && { echo "$d/$c"; return; }; done; done; }
OVMF_CODE=${OVMF_CODE:-$(find_ovmf)}
[ -n "$OVMF_CODE" ] || { echo "!! OVMF firmware not found (install edk2-ovmf / ovmf)" >&2; exit 1; }
OVMF_VARS_SRC=$(dirname "$OVMF_CODE")/OVMF_VARS.fd
[ -f "$OVMF_VARS_SRC" ] || OVMF_VARS_SRC=$(dirname "$OVMF_CODE")/OVMF_VARS_4M.fd

WORK=$(mktemp -d /tmp/asterkube-rubu.XXXXXX)
ESP="$WORK/esp"
mkdir -p "$ESP/EFI/BOOT" "$ESP/rubu"
cp "$EFI" "$ESP/EFI/BOOT/BOOTX64.EFI"
cp "$KERNEL" "$ESP/rubu/vmlinuz"
cp "$INITRD" "$ESP/rubu/initrd"
{
  echo '# rubu.toml (generated by boot-via-rubu.sh)'
  echo 'kernel  = "\rubu\vmlinuz"'
  echo 'initrd  = "\rubu\initrd"'
  echo "cmdline = \"$CMDLINE\""
  echo 'measure = true'
} > "$ESP/rubu/rubu.toml"
cp "$OVMF_VARS_SRC" "$WORK/vars.fd"

# Software TPM 2.0 so rubu's measured boot has somewhere to extend PCRs (rubu also
# ships its own CRB MMIO TPM driver when the firmware provides none).
SWTPM_PID=""
TPM_ARGS=()
if command -v swtpm >/dev/null; then
  SOCK="$WORK/swtpm.sock"; mkdir -p "$WORK/tpm"
  swtpm socket --tpmstate dir="$WORK/tpm" --ctrl type=unixio,path="$SOCK" --tpm2 --flags startup-clear >"$WORK/swtpm.log" 2>&1 &
  SWTPM_PID=$!
  for _ in $(seq 1 50); do [ -S "$SOCK" ] && break; sleep 0.1; done
  TPM_ARGS=(-chardev socket,id=chrtpm,path="$SOCK" -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-crb,tpmdev=tpm0)
else
  echo "==> swtpm not found; booting without a firmware TPM (rubu still measures via its own CRB driver if present)"
fi
cleanup() { [ -n "$SWTPM_PID" ] && kill "$SWTPM_PID" 2>/dev/null || true; }
trap cleanup EXIT

JOIN_ARGS=()
if [ -n "$JOIN_BUNDLE" ]; then
  [ -f "$JOIN_BUNDLE" ] || { echo "!! JOIN_BUNDLE=$JOIN_BUNDLE not found" >&2; exit 1; }
  echo "==> attaching cluster join bundle: $JOIN_BUNDLE (node will register + go Ready)"
  JOIN_ARGS=(-drive if=none,format=raw,id=join,file="$JOIN_BUNDLE"
             -device virtio-blk-pci,drive=join,serial=asterkubecfg,disable-legacy=on,disable-modern=off)
fi

ACCEL=(); CPU=(-cpu qemu64)
[ -w /dev/kvm ] && { ACCEL=(-accel kvm); CPU=(-cpu host); }
RUN=(qemu-system-x86_64)
[ "$TIMEOUT" != "0" ] && RUN=(timeout "$TIMEOUT" qemu-system-x86_64)

echo "==> booting asterkube THROUGH rubu (no GRUB2) — serial(rubu)=$WORK/serial.log kernel=$WORK/hvc0.log"
"${RUN[@]}" \
  -machine q35 "${ACCEL[@]}" "${CPU[@]},+x2apic" -m 4G -smp 2 --no-reboot -display none \
  -drive if=pflash,format=raw,unit=0,readonly=on,file="$OVMF_CODE" \
  -drive if=pflash,format=raw,unit=1,file="$WORK/vars.fd" \
  -drive format=raw,file=fat:rw:"$ESP" \
  "${TPM_ARGS[@]}" \
  -device virtio-serial,romfile= \
  -chardev file,id=hvc,path="$WORK/hvc0.log" -device virtconsole,chardev=hvc \
  -serial file:"$WORK/serial.log" -monitor none \
  "${JOIN_ARGS[@]}" \
  -netdev user,id=net01 \
  -device virtio-net-pci,netdev=net01,disable-legacy=on,disable-modern=off,mrg_rxbuf=off,ctrl_rx=off,event_idx=off,indirect_desc=off

echo "==> rubu console:"; sed 's/\x1b\[[0-9;]*[a-zA-Z]//g' "$WORK/serial.log" | grep -a . | sed -n '/Rubu\|rubu/,$p' | head -30
